### ISSUE TITLE
Convert Magnets Illustrator files to SVG.

### ISSUE THREAD

**Issue by worlduniting** [worlduniting/overcoffee.tv#4]
Current artwork source files are in an illustrator format. Rather than be locked into a proprietary (and expensive) vector graphics software, source files should be converted into SVG format. SVG can be edited with Open Source vector graphics software, like Inkscape.

Consider using the svgs themselves with png fallbacks. SVGs could eventually be dynamically created based upon CMS headings.

**Comment by dathompson** [comment]
Added few svg source file after converting fonts to outlines in commit d653930ffe2b042b50d809cce7a4d327dc43a321
